spring.application.name=incidencias

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/incidencias
spring.datasource.username=incidencias
spring.datasource.password=incidencias

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/schema,classpath:db/migration/data
